# Generated by Django 2.0.9 on 2019-01-21 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ico_portal.utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0017_default_owner_on_delete_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date',
            field=models.DateTimeField(default=ico_portal.utils.datetime.datetime.utcnow, verbose_name='Date'),
        ),
    ]
